sudo: false
os:
  - windows
dist: bionic
language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - CARGO_FEATURES=
  - CARGO_FEATURES=std
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true
install:
  - rustup component add clippy rustfmt
script:
  - cargo clippy --tests --features "$CARGO_FEATURES"
  - cargo test --features "$CARGO_FEATURES"
  - cargo doc --features "$CARGO_FEATURES"
  - cargo fmt --all -- --check
